# Generated by Django 5.2.5 on 2026-02-10 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ProgressTracker",
            "0002_rename_overall_progres_progresstracker_overall_progress",
        ),
        ("UserManagement", "0005_alter_teacher_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="progresstracker",
            name="student",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress_tracker",
                to="UserManagement.student",
            ),
        ),
    ]
