# Generated by Django 5.2.5 on 2026-02-10 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("PythonPlayground", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CodeSnippet",
        ),
    ]
